syself/charts

charts/cluster-api-bootstrap-provider-kubeadm/Chart.yaml
charts/cluster-api-controlplane-provider-kubeadm/Chart.yaml
charts/cluster-api-provider-hetzner/Chart.yaml
charts/cluster-api/Chart.yaml

Fixing naming as described here: https://helm.sh/docs/chart_best_practices/conventions/

:bug: Fix naming of charts

---

charts/cluster-api-bootstrap-provider-kubeadm/Chart.yaml
charts/cluster-api-controlplane-provider-kubeadm/Chart.yaml
charts/cluster-api-provider-hetzner/Chart.yaml
charts/cluster-api/Chart.yaml

Fixing the chart versioning in the cluster-api stack.

:bug: fix chart version

---

charts/cluster-api-bootstrap-provider-kubeadm/Chart.yaml
charts/cluster-api-controlplane-provider-kubeadm/Chart.yaml
charts/cluster-api-provider-hetzner/Chart.yaml
charts/cluster-api/Chart.yaml

:seedling: adding keyword

---

charts/monochart/Chart.yaml

Fixes an issue by referencing the v0.2.0 version of the monochart.

:bug: fixing monochart semver

---

charts/csi-hcloud/.helmignore
charts/csi-hcloud/Chart.yaml
charts/csi-hcloud/templates/csi-driver.yaml
charts/csi-hcloud/templates/daemonset.yaml
charts/csi-hcloud/templates/rbac.yaml
charts/csi-hcloud/templates/service.yaml
charts/csi-hcloud/templates/serviceMonitor.yaml
charts/csi-hcloud/templates/statefulset.yaml
charts/csi-hcloud/templates/storageClass.yaml
charts/csi-hcloud/values.yaml

:sparkles: adding csi-hcloud

---

charts/ccm-hcloud/Chart.yaml
charts/ccm-hcloud/templates/deployment.yaml
charts/ccm-hcloud/values.yaml

Updating and settings new defaults for hcloud-ccm

:seedling: updating and setting new defaults

---

charts/csi-hcloud/Chart.yaml
charts/csi-hcloud/templates/statefulset.yaml

:seedling: Updating csi-hcloud chart

---

charts/capi-cr/Chart.yaml
charts/capi-cr/templates/cluster.x-k8s.io/cluster.yaml
charts/capi-cr/templates/infrastructure_ref.tpl
charts/capi-cr/templates/kubeadm.tpl

Fixes name generation in infraRef and bootstrapRef

:bug: Fixes name generation in infraRef and bootstrapRef

---

charts/capi-cr/Chart.yaml
charts/capi-cr/templates/cluster.x-k8s.io/machine_deployment.yaml
charts/capi-cr/templates/cluster.x-k8s.io/machine_health_check.yaml

Fixing generated clusterName in MD and MHC

:bug: Fixing generated clusterName in MD and MHC

---

charts/ccm-hcloud/Chart.yaml

Updating the Chart version for regenerating the release because release not showing up in chart repo

:bug: Release not showing up in chart repo

---

charts/ccm-hcloud/Chart.yaml
charts/ccm-hcloud/values.yaml

Adding docker.io to the image name

:seedling: Adding docker.io to the image name

---

charts/capi-cr/Chart.yaml
charts/konnectivity-agent/.helmignore
charts/konnectivity-agent/Chart.yaml
charts/konnectivity-agent/templates/_helpers.tpl
charts/konnectivity-agent/templates/deployment.yaml
charts/konnectivity-agent/templates/rbac.yaml
charts/konnectivity-agent/templates/serviceaccount.yaml
charts/konnectivity-agent/values.yaml

Adds the konnectivity-agent helm chart

:sparkles: Adding konnectivity-agent helm chart

---

charts/raw/.helmignore
charts/raw/Chart.yaml
charts/raw/templates/_helpers.tpl
charts/raw/templates/manifests.yaml
charts/raw/values.yaml

:sparkles: Adding raw chart

---

charts/capi-cr/Chart.yaml
charts/capi-cr/templates/cluster.x-k8s.io/machine_health_check.yaml

Fixing MachineHealthCheck as the label changed from nodepool to cluster.x-k8s.io/deployment-name

:bug: Fixing MachineHealthCheck

---

charts/raw/templates/manifests.yaml

Fixing new line issue in raw chart

:bug: fix multiple manifests new line

---

charts/raw/Chart.yaml

:seedling: bump chart to new version

---

charts/ccm-hcloud/Chart.yaml
charts/ccm-hcloud/templates/pdb.yaml
charts/ccm-hcloud/values.yaml

:sparkles: Adding pdb to ccm-hcloud

---

.github/workflows/release.yaml

fixes action by adding dependencies

:bug: fixes action by adding dependencies

---

charts/ccm-hcloud/Chart.yaml
charts/ccm-hcloud/templates/deployment.yaml
charts/ccm-hcloud/values.yaml

Fixes affinity and adds opinionated defaults

:bug: Fixes affinity and adds opinionated defaults

---

charts/csi-hcloud/Chart.yaml
charts/csi-hcloud/templates/daemonset.yaml
charts/csi-hcloud/templates/pdb.yaml
charts/csi-hcloud/templates/statefulset.yaml
charts/csi-hcloud/values.yaml

csi-hcloud adding some defaults

:seedling: csi-hcloud adding some defaults

---

charts/ccm-hcloud/Chart.yaml
charts/ccm-hcloud/templates/deployment.yaml
charts/ccm-hcloud/templates/pdb.yaml
charts/ccm-hcloud/values.yaml

fix tolerations and add minAvailable in pdb

:bug: fix tolerations and add minAvailable in pdb

---

charts/konnectivity-agent/Chart.yaml
charts/konnectivity-agent/templates/pdb.yaml

:seedling: adding minAvailable in pdb

---

charts/ccm-hcloud/Chart.yaml

Bumping chart version as release was not successful

:bug: Bumping chart version as release was not successful

---

charts/ccm-hetzner/Chart.yaml
charts/ccm-hetzner/values.yaml

:seedling: Updating the ccm-hetzner image

---

charts/monochart/Chart.yaml
charts/monochart/ci/full-common.yaml
charts/monochart/templates/ingress.yaml
charts/monochart/templates/regcred-secret.yaml

/kind other           
updates ingress and fixes some minor issues

:seedling: bump new version

---

charts/konnectivity-agent/Chart.yaml
charts/konnectivity-agent/templates/deployment.yaml

/kind other             
konnectivity update

:seedling: update konnectivity

---

charts/ccm-hetzner/Chart.yaml
charts/ccm-hetzner/values.yaml

/kind other       
Updates the image for hetzner ccm.

:seedling: release new ccm-hetzner version

---

charts/ccm-hetzner/Chart.yaml
charts/ccm-hetzner/values.yaml

/kind other     
* Updates image of hetzner ccm

:seedling: update image

---

charts/argocd-cr/Chart.yaml
charts/argocd-cr/ci/example.yaml
charts/argocd-cr/templates/_helpers.tpl
charts/argocd-cr/templates/argo-application.yaml
charts/argocd-cr/templates/argo-project.yaml

/kind feature           
Adds the argocd-cr helm chart

:sparkles: adding argocd-cr

---

charts/argocd-cr/Chart.yaml

/kind bug           
Fixes wrong name in chart.yaml

:seedling: fixing name

---

charts/csi-hcloud/Chart.yaml
charts/csi-hcloud/templates/controller-deployment.yaml
charts/csi-hcloud/templates/csi-driver.yaml
charts/csi-hcloud/templates/node-daemonset.yaml
charts/csi-hcloud/values.yaml

/kind other          
Upgrades to v2.1.0 of csi-hcloud
Fixes #
**TODOs**:

:sparkles: upgrade csi-hcloud

---

charts/csi-hcloud/Chart.yaml
charts/csi-hcloud/templates/controller-rbac.yaml
charts/csi-hcloud/templates/node-daemonset.yaml

/kind bug              
Fixes csi
Fixes #
**TODOs**:

:seedling: fix csi

---

charts/ccm-hetzner/Chart.yaml
charts/ccm-hetzner/values.yaml

/kind other            
Updates to v1.13.2

:seedling: update ccm

---

charts/ccm-hetzner/Chart.yaml

Updates the ccm-hetzner to fix a missing v in the appversion
Fixes #
**TODOs**:

:seedling: update ccm-hetzner

---

.vscode/settings.json
charts/ccm-hetzner-test/.helmignore
charts/ccm-hetzner-test/Chart.yaml
charts/ccm-hetzner-test/templates/_helpers.tpl
charts/ccm-hetzner-test/templates/deployment.yaml
charts/ccm-hetzner-test/templates/pdb.yaml
charts/ccm-hetzner-test/templates/secret.yaml
charts/ccm-hetzner-test/templates/serviceaccount.yaml
charts/ccm-hetzner-test/values.yaml

A new chart was added to test the new hetzner-ccm.
Related: https://github.com/syself/hetzner-cloud-controller-manager/tree/new-rebase

:seedling: added ccm-hetzner-test for testing.

---

charts/konnectivity-agent/Chart.yaml

:seedling: New version of konnectivity-agent

:seedling: New version of konnectivity-agent

---

charts/ccm-hetzner/Chart.yaml

:seedling: new version of ccm-hetzner

:seedling: new version of ccm-hetzner

---

charts/hcloud-csi/Chart.yaml

:seedling: new version of hcloud-csi

:seedling: new version of hcloud-csi

---

charts/hcloud-csi/Chart.yaml

:seedling: fixed version of csi.

:seedling: fixed version of csi.

---

charts/hcloud-csi/Chart.yaml
charts/hcloud-csi/values.yaml

:seedling: add v for csi driver.

:seedling: add v for csi driver.

---

charts/ccm-hetzner/Chart.yaml
charts/ccm-hetzner/templates/deployment.yaml

Adds a taint for cluster-api and releases a new ccm version
Fixes #
**TODOs**:

:seedling: update ccm version

---

charts/ccm-hetzner/Chart.yaml
charts/ccm-hetzner/templates/_helpers.tpl
charts/ccm-hetzner/templates/deployment.yaml
charts/ccm-hetzner/values.yaml

Adding envVars to ccm
Fixes #
**TODOs**:

:seedling: adding extraEnvVars to ccm

---

charts/hcloud-csi/templates/node/daemonset.yaml
charts/hcloud-csi/values.yaml

/kind feature
/kind api-change
fixes #62: Add a parameter `node.kubeletDir` to set the kubeletDir the csi-node is using. 
**TODOs**:

✨ make kubeletDir configurable with values.yaml

---

charts/konnectivity-agent/Chart.yaml
charts/konnectivity-agent/values.yaml

Adding konnectivity agent default
Fixes #
**TODOs**:

:seedling: removing autoscaler as a default

---

charts/ccm-hetzner/Chart.yaml

Updates the ccm-hetzner image to the version v1.18.0-0.0.5
Fixes #
**TODOs**:

:seedling: updating ccm hetzner to version v1.18.0-0.0.5

---

charts/konnectivity-agent/templates/deployment.yaml
charts/konnectivity-agent/values.yaml

Adds topologySpreadConstraints
Fixes #
**TODOs**:

:seedling: refactoring and adding topologySpreadConstraints

---

charts/konnectivity-agent/Chart.yaml

releases konnectivity-agent helm chart
Fixes #
**TODOs**:

:seedling: releasing new version of konnectivity-agent helm chart

---

charts/konnectivity-agent/Chart.yaml
charts/konnectivity-agent/templates/deployment.yaml

:seedling: adding env variables to konnectivity-agent

---

charts/ccm-hetzner/Chart.yaml

`image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
`

🌱 update ccm hetzner helm chart

---

charts/ccm-hetzner/Chart.yaml

🌱 update ccm-hetzner helm chart to v1.18.0-0.0.7

---

charts/konnectivity-agent/Chart.yaml
charts/konnectivity-agent/values.yaml

```bash
$ crane ls registry.k8s.io/cpa/cluster-proportional-autoscaler
...
v1.8.9
```

🌱 update cluster-proportional-autoscaler helm chart

---

charts/topolvm/Chart.yaml
charts/topolvm/values.yaml

:seedling: typo in deviceClass (volume)

---

charts/ccm-hetzner/Chart.yaml
charts/ccm-hetzner/templates/deployment.yaml

This reverts commit 72e068797c909ff42aa1346426eef0f37925f9be.
Related to #92 
**TODOs**:

🌱 Revert remove deprecated flag from ccm

---

charts/ccm-hetzner/Chart.yaml

🌱 update ccm-hetzner chart to 1.1.15

---

charts/konnectivity-agent/templates/deployment.yaml
charts/konnectivity-agent/templates/server-service.yaml

🌱 add readinessProbe for konnectivity-agent deployment

---

charts/ccm-hetzner/Chart.yaml
charts/ccm-hetzner/templates/deployment.yaml
charts/ccm-hetzner/templates/secret.yaml
charts/ccm-hetzner/values.yaml

This PR updates Syself Hetzner ccm to v2. This introduces hot reloading of credentials.
Related PR: https://github.com/syself/hetzner-cloud-controller-manager/pull/49

:seedling: Syself Hetzner ccm v2. Hot reload via mounted secret.

---

charts/vaultwarden/Chart.yaml

appVersion is added to Chart.yaml of vaultwarden charts
Fixes #
**TODOs**:

:seedling: appVersion is added to Chart.yaml of vaultwarden charts

---

charts/hcloud-csi/Chart.yaml
charts/hcloud-csi/values.yaml

Updates hetzner csi driver from 2.11.0 to 2.12.0

🌱 Update CSI driver

---

charts/konnectivity-agent/values.yaml

Changes proportional autoscaler for konnectivity to ladder mode

🌱 Use ladder scaling for konnectivity

---

README.md

:book: Added README
